service: default
runtime: java11
instance_class: F1

handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html
    redirect_http_response_code: 301
    secure: always

  - url: /(.*\.(html|png|map|js|gif|ico|eot|woff|woff2|otf|txt|ttf|css|jpg|svg|xlsx|webmanifest))
    static_files: www/\1
    upload: www/(.*\.(html|png|map|js|gif|ico|eot|woff|woff2|otf|txt|ttf|css|jpg|svg|xlsx|webmanifest))
    redirect_http_response_code: 301
    secure: always
